import { readdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"

/**
 * Generates `registry/examples.generated.ts`: a map from `<component>/<example>` to a dynamic
 * import, so component pages can render examples without a hand-maintained list. Run with
 * `pnpm examples:build`; a test fails when the map is stale.
 */
export function renderExamplesIndex(
  root = new URL("../registry/examples/", import.meta.url).pathname
): string {
  const entries: string[] = []
  for (const component of readdirSync(root, { withFileTypes: true })) {
    if (!component.isDirectory()) continue
    for (const file of readdirSync(join(root, component.name))) {
      if (!file.endsWith(".tsx")) continue
      const example = file.replace(/\.tsx$/, "")
      entries.push(
        `  '${component.name}/${example}': () => import('./examples/${component.name}/${example}'),`
      )
    }
  }
  entries.sort()
  return `// Generated by scripts/examples-index.ts — run \`pnpm examples:build\` after adding an example.
import type { ComponentType } from 'react'

export const examples: Record<string, () => Promise<{ default: ComponentType }>> = {
${entries.join("\n")}
}
`
}

if (
  process.argv[1] &&
  import.meta.url === new URL(process.argv[1], "file://").href
) {
  const target = new URL("../registry/examples.generated.ts", import.meta.url)
  writeFileSync(target, renderExamplesIndex())
  console.log(`wrote ${target.pathname}`)
}
